### ISSUE TITLE
kedro databricks bundle broken for custom task_key

### ISSUE THREAD

**Issue by lucsoret** [JenspederM/kedro-databricks#110]
Let's say I have a pipeline defined in Kedro `my_pipeline` thas has two tasks `taskA` and `taskB`

If my file `conf/base/databricks` is something like 
```yaml
my_pipeline:
  tasks:
    - task_key: default 
      run_if: AT_LEAST_ONE_SUCCESS
      package_name: my_package
```
the command : 
`poetry run kedro databricks bundle --env=local --overwrite --conf=conf/my_pipeline --pipeline=my_pipeline`
will generate the appropriate ressource file : 
```yaml
resources:
    jobs:
        my_pipeline:
            name: my_pipeline
            tasks:
            -   task_key: taskA
                run_if: AT_LEAST_ONE_SUCCESS
                package_name: my_package
            -   task_key: taskB
                run_if: AT_LEAST_ONE_SUCCESS
                package_name: my_package
```

However If I just want to add the parameter AT_LEAST_ONE_SUCCESS to the `taskB` : 
```yaml
my_pipeline:
  tasks:
    - task_key: default 
      package_name: my_package
    - task_key: taskB 
      run_if: AT_LEAST_ONE_SUCCESS
```

The run_if condition won't be added to `taskB` : 
```yaml
resources:
    jobs:
        my_pipeline:
            name: my_pipeline
            tasks:
            -   task_key: taskA
                package_name: my_package
            -   task_key: taskB
                package_name: my_package
```

That's the same if I simply do : 
```yaml
my_pipeline:
  tasks:
    - task_key: taskB 
      run_if: AT_LEAST_ONE_SUCCESS
```
So it seems there is an issue with the `databricks bundle` when overriding an other task that the default one

**Comment by JenspederM** [comment]
Hi @lucsoret ,

Thank you for raising this PR. I'm trying to work on a complete reimplementation of the bundling logic. But it's unfortunately not an easy problem, so it might take a little time.

I'm unsure whether I'll make this as part of version 8.0.0, if not it will come in the near future.

Again thank for letting me know, and for proving such an in depth example. 😊

**Comment by JenspederM** [comment]
Hi @lucsoret - Version 0.8.0 is now released and this issue should have been solved. 

Please let me know, if that is not the case

**Comment by JenspederM** [comment]
@npfp Can you provide an example of the overrides you're trying to make?

**Comment by npfp** [comment]
Sure, it would be something like:


```
default:
  webhook_notifications:
    on_failure:
      - id: NOTIFICATION_SOURCE_ID
  tasks:
    - task_key: default # will be applied to all tasks in the specified workflow
      existing_cluster_id: CLUSTER_ID
      libraries:
        - whl: /Workspace/packages/internal-package-0.1.1-py3-none-any.whl
        - whl: ../dist/*.whl
```

**Comment by JenspederM** [comment]
@npfp 

This should now be resolved.

**Comment by npfp** [comment]
That's great many thx!

cc: @lucsoret

**Comment by npfp** [comment]
Hi @JenspederM 

We tried to use main but now got a similar error :


```
                                                                              │
│    35 def _get_lookup_key(key: str):                                         │
│    36 │   lookup = OVERRIDE_KEY_MAP.get(key)                                 │
│    37 │   if lookup is None:                                                 │
│ ❱  38 │   │   raise ValueError(f"Key {key} not found in OVERRIDE_KEY_MAP")   │
│    39 │   return lookup                                                      │
│    40                                                                        │
│    41                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Key libraries not found in OVERRIDE_KEY_MAP
```

Due to the same override than previous. 

(as we depend on a private package that must be installed to run the wheel, we must override the `librairies` )

**Comment by JenspederM** [comment]
Okay. Can you provide an example of the config? 😊

Don't know if you've noticed, but I've started implementing tests for bundling through examples. So whenever you have a problem like this, an override example would be nice as it helps me zone in on the underlying issue

**Comment by npfp** [comment]
Yes I saw this, that's a great idea! :-) 

It should be exactly the same config override :

```yaml
default:
  webhook_notifications:
    on_failure:
      - id: NOTIFICATION_SOURCE_ID
  tasks:
    - task_key: default # will be applied to all tasks in the specified workflow
      existing_cluster_id: CLUSTER_ID
      libraries:
        - whl: /Workspace/packages/internal-package-0.1.1-py3-none-any.whl
        - whl: ../dist/*.whl
```

**Comment by JenspederM** [comment]
@npfp version 0.9.0 is now released 😊

**Comment by npfp** [comment]
That is so great! Thank you very much!

**Comment by npfp** [comment]
There's only one little issue (but it's because we didn't manage to fid a proper way to deal with private repo packages in databricks..):


when we pass 
```yaml
default:
  tasks:
    - task_key: default # will be applied to all tasks in the specified workflow
      libraries:
        - whl: /Workspace/packages/internal-package-0.1.1-py3-none-any.whl
        - whl: ../dist/*.whl
```

the plugin now generates :

```yaml
  tasks:
      libraries:
        - whl: ../dist/*.whl
        - whl: /Workspace/packages/internal-package-0.1.1-py3-none-any.whl
```

This is an issue for us because of an ugly hack where we remove the private GitHub repo link from the requirements (didn't manage to make it work), and so rely on the order to ensure that the packages are correctly installed.

I suppose in the plugin code, there's now a sort that reorder the libraries list which is inconvenient for us. Any chance we could keep the order as the user provides it ?



[Also if you have any tricks on how to properly deal with installation of private repository within databricks, don't hesitate :-)]
