### ISSUE TITLE
Credentials are not found anymore

### ISSUE THREAD

**Issue by npfp** [JenspederM/kedro-databricks#118]
Hello @jpm-halfspace ,

After having upgraded the plugin to the last version we're having these kind of errors:

```python
KeyError: "Unable to find credentials 'provider_credentials': check your data catalog and credentials configuration. See https://kedro.readthedocs.io/en/stable/kedro.io.DataCatalog.html for an example."
```

Indeed we rely on the credential file to retrieve databricks secrets:

```yaml
provider_credentials:
  user: ${databricks_secret:provider,client_id}
  password: ${databricks_secret:provider,client_secret}
```

Could it be that now the plugin doesn't copy the credential file on dbfs when it used to do it?
