### ISSUE TITLE
`kedro databricks init` will break an existing `conf/base/databricks.yml` file

### ISSUE THREAD

**Issue by astrojuanlu** [JenspederM/kedro-databricks#2]
I was following the steps, and after `kedro databricks init`, `kedro databricks bundle` failed:

```
$ kedro new --starter=databricks-iris && cd ...
$ kedro databricks init
$ kedro databricks bundle
...
ConstructorError: while constructing a mapping
  in "<file>", line 1, column 1
found duplicate key default
  in "<file>", line 13, column 1
```

It turns out that PyYAML can read the `databricks.yml` file just fine:

```
In [9]: import yaml

In [10]: with open("conf/base/databricks.yml") as fh:
    ...:     conf = yaml.load(fh, Loader=yaml.SafeLoader)
    ...: 

In [11]: print(conf)
{'default': {'job_clusters': [{'job_cluster_key': 'default', 'new_cluster': {'spark_version': '14.3.x-scala2.12', 'node_type_id': 'Standard_D4ds_v4', 'num_workers': 1, 'spark_env_vars': {'KEDRO_LOGGING_CONFIG': '/dbfs/FileStore/test_databricks_iris/conf/logging.yml'}}}], 'tasks': [{'task_key': 'default', 'job_cluster_key': 'default'}]}}
```

but OmegaConf cannot:

```pytb
In [12]: from omegaconf import OmegaConf

In [13]: OmegaConf.load("conf/base/databricks.yml")
---------------------------------------------------------------------------
ConstructorError                          Traceback (most recent call last)
Cell In[13], line 1
----> 1 OmegaConf.load("conf/base/databricks.yml")

File ~/.micromamba/envs/pyspark/lib/python3.11/site-packages/omegaconf/omegaconf.py:190, in OmegaConf.load(file_)
    188 if isinstance(file_, (str, pathlib.Path)):
    189     with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
--> 190         obj = yaml.load(f, Loader=get_yaml_loader())
    191 elif getattr(file_, "read", None):
    192     obj = yaml.load(file_, Loader=get_yaml_loader())

File ~/.micromamba/envs/pyspark/lib/python3.11/site-packages/yaml/__init__.py:81, in load(stream, Loader)
     79 loader = Loader(stream)
     80 try:
---> 81     return loader.get_single_data()
     82 finally:
     83     loader.dispose()

File ~/.micromamba/envs/pyspark/lib/python3.11/site-packages/yaml/constructor.py:51, in BaseConstructor.get_single_data(self)
     49 node = self.get_single_node()
     50 if node is not None:
---> 51     return self.construct_document(node)
     52 return None

File ~/.micromamba/envs/pyspark/lib/python3.11/site-packages/yaml/constructor.py:60, in BaseConstructor.construct_document(self, node)
     58     self.state_generators = []
     59     for generator in state_generators:
---> 60         for dummy in generator:
     61             pass
     62 self.constructed_objects = {}

File ~/.micromamba/envs/pyspark/lib/python3.11/site-packages/yaml/constructor.py:413, in SafeConstructor.construct_yaml_map(self, node)
    411 data = {}
    412 yield data
--> 413 value = self.construct_mapping(node)
    414 data.update(value)

File ~/.micromamba/envs/pyspark/lib/python3.11/site-packages/omegaconf/_utils.py:144, in get_yaml_loader.<locals>.OmegaConfLoader.construct_mapping(self, node, deep)
    142         continue
    143     if key_node.value in keys:
--> 144         raise yaml.constructor.ConstructorError(
    145             "while constructing a mapping",
    146             node.start_mark,
    147             f"found duplicate key {key_node.value}",
    148             key_node.start_mark,
    149         )
    150     keys.add(key_node.value)
    151 return super().construct_mapping(node, deep=deep)

ConstructorError: while constructing a mapping
  in "/Users/juan_cano/Projects/QuantumBlackLabs/tmp/test-databricks-iris/conf/base/databricks.yml", line 1, column 1
found duplicate key default
  in "/Users/juan_cano/Projects/QuantumBlackLabs/tmp/test-databricks-iris/conf/base/databricks.yml", line 13, column 1
```

Here's the resulting file:

```yaml
default:
    job_clusters:
    -   job_cluster_key: default
        new_cluster:
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_D4ds_v4
            num_workers: 1
            spark_env_vars:
                KEDRO_LOGGING_CONFIG: /dbfs/FileStore/test_databricks_iris/conf/logging.yml
    tasks:
    -   task_key: default
        job_cluster_key: default
default:
    job_clusters:
    -   job_cluster_key: default
        new_cluster:
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_D4ds_v4
            num_workers: 1
            spark_env_vars:
                KEDRO_LOGGING_CONFIG: /dbfs/FileStore/test_databricks_iris/conf/logging.yml
    tasks:
    -   task_key: default
        job_cluster_key: default
```
