### ISSUE TITLE
conf source location doesn't exist

### ISSUE THREAD

**Issue by puneeter** [JenspederM/kedro-databricks#33]
## Description

My resource file:

```yaml
resources:
    jobs:
        job_name:
            name: job_name
            tasks:
            -   task_key: job_name_raw
                depends_on: []
                python_wheel_task:
                    package_name: my_package
                    entry_point: databricks_run
                    parameters:
                    - --nodes
                    - nodes.raw
                    - --conf-source
                    - /dbfs/FileStore/my_package/conf
                    - --package-name
                    - my_package
                libraries:
                -   whl: ../dist/*.whl
                -   whl: "/Workspace/Users/my_username/.bundle/package_name/dev/files/extra_packages/package_1/package_1.whl"
```

Error:

```
MissingConfigException: Given configuration path either does not exist or is not a valid directory: /dbfs/FileStore/my_package/conf/base
```

Are using the right path for conf_source here?
