### ISSUE TITLE
Ability to merge some config?

### ISSUE THREAD

**Issue by npfp** [JenspederM/kedro-databricks#37]
Is there a way to modify some part of the default config rather that overriding it?

For example, the user could want to have a default version of the cluster configuration and only change one specific field (for example specific `spark_env_vars`) in the env configuration.

For example, if there is these definitions in `conf/base/databricks.yml`

```yaml
default:
    job_clusters:
        - job_cluster_key: default
          new_cluster:
              spark_version: 15.3.x-scala2.12
              node_type_id: m4.large
              num_workers: 0
              runtime_engine: STANDARD
              data_security_mode: LEGACY_SINGLE_USER
              spark_env_vars:
                  KEDRO_LOGGING_CONFIG: "/dbfs/FileStore/david/conf/logging.yml"
              enable_elastic_disk: true
              spark_conf:
                  spark.databricks.cluster.profile: singleNode
                  spark.master: "local[*,4]"
              custom_tags:
                  ResourceClass: SingleNode
```

and in `conf/provider/databricks.yml`

```yaml
provider:
    job_clusters:
        - job_cluster_key: default
          new_cluster:
              spark_env_vars:
                   PROVIDER_USERNAME: username
                   PROVIDER_PASSWORD: password
```

then the job definition would be

```yaml
resources:
    jobs:
       provider:
            name: provider
            job_clusters:
            -   job_cluster_key: default
                new_cluster:
                    spark_version: 15.3.x-scala2.12
                    node_type_id: m4.large
                    num_workers: 0
                    runtime_engine: STANDARD
                    data_security_mode: LEGACY_SINGLE_USER
                    spark_env_vars:
                        KEDRO_LOGGING_CONFIG: /dbfs/FileStore/david/conf/logging.yml
                        PROVIDER_USERNAME: username
                        PROVIDER_PASSWORD: password
                    enable_elastic_disk: true
                    spark_conf:
                        spark.databricks.cluster.profile: singleNode
                        spark.master: local[*,4]
                    custom_tags:
                        ResourceClass: SingleNode
```
